import{state,char,thread,persona,memories,lore,extras,guides,presets,uid,now,saveSoon,edge,esc}from'./core.js';
import{widgetPrompt,parseWidgetBlock,widgetsHtml}from'./widgets.js';
const words=s=>String(s||'').toLowerCase().split(/[^\p{L}\p{N}_]+/u).filter(x=>x.length>1);
function selectedLore(c,th,input=''){const all=lore(c),hay=words([input,...th.messages.slice(-6).map(m=>m.content)].join(' '));return all.filter(x=>{const policy=x.readPolicy||x.mode||'auto';if(policy==='required'||policy==='always')return true;if(policy==='manual')return (th.manualLoreIds||[]).includes(x.id);if(policy==='keyword'){const ks=x.triggerKeywords||x.keywords||[];return ks.some(k=>hay.some(t=>t.includes(String(k).toLowerCase())||String(k).toLowerCase().includes(t)))}return true}).slice(0,18)}
function selectedGuides(c,th,input=''){const all=guides(c),hay=String([input,...th.messages.slice(-4).map(m=>m.content)].join(' ')).toLowerCase();return all.filter(x=>{const p=x.readPolicy||'required';if(p==='manual')return (th.manualGuideIds||[]).includes(x.id);if(p==='keyword')return (x.triggerKeywords||[]).some(k=>hay.includes(String(k).toLowerCase()));return true}).slice(0,16)}
function systemPrompt(c,th,input=''){const p=persona(th),mem=memories(c,th),lr=selectedLore(c,th,input),ex=extras(c),gs=selectedGuides(c,th,input),pre=state.presets.find(x=>x.id===th.activePresetId),w=state.works.find(x=>x.id===th.workId);return[
`당신은 LumiChat 역할극의 메인 캐릭터 '${c.name}'이다.`,w?`작품: ${w.title}\n${w.description||''}`:'',`캐릭터 설명: ${c.description||''}`,`외모: ${c.appearance||''}`,`성격: ${c.personality||''}`,`가치관/목표: ${c.values||''} ${c.desires||''}`,`말투: ${c.speechStyle||''}`,`관계: ${c.relationship||c.initialRelation||''}`,`문체: ${c.perspective||'3인칭'}, ${c.responseLength||'중간'}, 대사·지문 ${c.narrationRatio||'균형'}`,c.narrativeInstructions||'',c.userAgencyRules||'사용자의 대사·행동·감정·속마음을 임의로 확정하지 않는다.',c.outputFormat||'',c.contentRules||'',
 p?`플레이어 프로필(${p.name||'사용자'}):\n외형: ${p.appearance||''}\n성격: ${p.personality||''}\n말투: ${p.speech||''}\n배경: ${p.background||p.description||p.content||''}\n현재 관계: ${p.relationship||''}\n현재 상태: ${p.currentState||''}\n숨기는 사실: ${p.hiddenFacts||''}\n사용자 주도권: ${p.agencyRules||''}`:'',
 th?.scene?`현재 장면: 날짜 ${th.scene.date||'미정'} / 시간 ${th.scene.time||'미정'} / 장소 ${th.scene.location||'미정'} / 상태 ${th.scene.state||''}`:'',
 ex.length?`등장 가능한 인물(초기 선택 불필요, 스토리상 필요할 때 자연스럽게 등장):\n${ex.map(x=>`- ${x.name}${x.role?`(${x.role})`:''}: ${x.description||x.content||''}\n  말투: ${x.speech||''}\n  관계: ${x.relationships||''}\n  알고 있음: ${x.knownFacts||''}\n  모름: ${x.unknownFacts||''}`).join('\n')}`:'',
 gs.length?`출력 지침:\n${gs.map(x=>`- ${x.title}: ${x.content}`).join('\n')}`:'',lr.length?`세계관·사건 자료:\n${lr.map(x=>`- [${x.collectionType||'world'}] ${x.title||x.name}: ${x.content||''}`).join('\n')}`:'',mem.length?`장기 기억(연속성 유지):\n${mem.map(x=>`- ${x.title||'기억'}: ${x.content}`).join('\n')}`:'',pre?.instructions?`현재 응답 프리셋: ${pre.name}\n${pre.instructions}`:'',widgetPrompt(th),`대사와 지문에서 누가 말하는지 독자가 알 수 있게 한다. 메인 캐릭터 외 인물이 말하면 이름을 자연스럽게 명시한다.`].filter(Boolean).join('\n\n')}
export async function send(text='',regenId=null){const c=char(),th=thread();if(!c||!th)throw new Error('대화방을 먼저 선택해 주세요.');if(regenId){const i=th.messages.findIndex(m=>m.id===regenId);if(i>=0)th.messages.splice(i,1)}else if(text.trim())th.messages.push({id:uid('msg'),role:'user',content:text.trim(),createdAt:now()});const recent=th.messages.slice(-(state.settings.recentMessageCount||24)).map(m=>({role:m.role==='assistant'?'assistant':'user',content:m.content}));const pre=state.presets.find(x=>x.id===th.activePresetId),provider=th.provider||pre?.provider||c.defaultProvider||state.settings.defaultProvider||'google',model=th.activeModel||pre?.model||c.defaultModel||state.settings.defaultModel||'gemini-3.6-flash',temperature=Number(pre?.temperature??state.settings.temperature??.85),maxTokens=Number(pre?.maxTokens??state.settings.maxTokens??2500);const r=await edge('chat',{provider,model,temperature,maxTokens,messages:[{role:'system',content:systemPrompt(c,th,text)},...recent]});const parsed=parseWidgetBlock(r.content,th);th.messages.push({id:uid('msg'),role:'assistant',content:parsed.content||r.content,createdAt:now(),model:r.model||model,provider,usage:r.usage||null,statusWidgetSnapshots:parsed.snapshots||null});th.updatedAt=now();saveSoon();return r}
export function editMessage(id,text){const th=thread(),m=th?.messages.find(x=>x.id===id);if(!m)return;m.content=text.trim();m.editedAt=now();saveSoon()}
export function deleteMessage(id){const th=thread();if(!th)return;th.messages=th.messages.filter(x=>x.id!==id);saveSoon()}
export async function extractMemory(count=16){const c=char(),th=thread();if(!c||!th)throw new Error('대화가 없어요.');const msgs=th.messages.slice(-Math.max(2,count));if(msgs.length<2)throw new Error('기억으로 정리할 대화가 아직 부족해요.');const r=await edge('memory-extract',{provider:state.settings.memoryProvider||state.settings.defaultProvider,model:state.settings.memoryModel||state.settings.defaultModel,characterName:c.name,personaName:persona(th)?.name||state.profile.name||'사용자',range:{label:`최근 ${msgs.length}개 메시지`,startPreview:msgs[0]?.content?.slice(0,100),endPreview:msgs.at(-1)?.content?.slice(0,100)},messages:msgs.map(m=>({role:m.role,content:m.content}))});for(const m of r.memories||[])state.memories.push({id:uid('memory'),characterId:c.id,threadId:null,status:'candidate',enabled:true,pinned:false,scope:'character',useCount:0,createdAt:now(),updatedAt:now(),sourceThreadId:th.id,sourceMessageIds:msgs.map(x=>x.id),...m});th.lastMemoryExtractionMessageId=msgs.at(-1)?.id||null;saveSoon();return r}
export function messageHtml(m,c){const th=thread(),p=persona(th),who=m.role==='user'?(p?.name||state.profile.name||'사용자'):(m.speakerName||c?.name||'캐릭터');return`<article class="msg ${m.role}" data-id="${m.id}"><header><b>${esc(who)}</b><span>${new Date(m.createdAt||Date.now()).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</span></header><div class="msg-body">${esc(m.content).replace(/\n/g,'<br>')}</div><footer><button data-act="copy">복사</button><button data-act="edit">수정</button><button data-act="delete">삭제</button>${m.role==='assistant'?'<button data-act="regen">재생성</button>':''}</footer>${m.role==='assistant'?widgetsHtml(m,th):''}</article>`}
