import{demoSeed}from'./demo.js';
const EDGE='https://vulpttgewjfkxojimyxl.supabase.co/functions/v1/lumichat-mobile';
const STATE_KEY='lumichat-mobile-state-v19';const LEGACY_KEY='lumichat-mobile-state-v18';const DEV_KEY='lumichat-device-token-v1';
const EDGE_TIMEOUT=12000,BOOT_TIMEOUT=2800;
export const $=(q,r=document)=>r.querySelector(q);export const $$=(q,r=document)=>[...r.querySelectorAll(q)];
export const uid=(p='id')=>`${p}_${Date.now().toString(36)}_${crypto.randomUUID().slice(0,8)}`;
export const now=()=>new Date().toISOString();export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const clone=v=>JSON.parse(JSON.stringify(v));
const arr=v=>Array.isArray(v)?v:[];
function token(){let t=localStorage.getItem(DEV_KEY)||'';if(!/^[A-Za-z0-9_-]{32,160}$/.test(t)){const b=new Uint8Array(32);crypto.getRandomValues(b);t=btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');localStorage.setItem(DEV_KEY,t)}return t}
export async function edge(action,payload={},timeoutMs=EDGE_TIMEOUT){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);let r;try{r=await fetch(EDGE,{method:'POST',headers:{'content-type':'application/json','x-lumichat-device':token()},body:JSON.stringify({action,...payload}),cache:'no-store',signal:controller.signal})}catch(e){if(e?.name==='AbortError')throw new Error('모바일 서버 응답이 늦어 요청을 중단했어요. 잠시 후 다시 시도해 주세요.');throw new Error('모바일 서버에 연결하지 못했어요. 인터넷 연결을 확인해 주세요.')}finally{clearTimeout(timer)}let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.error||`요청 실패 (${r.status})`);e.status=r.status;e.code=d.code;e.data=d;throw e}return d}
export function fresh(){const t=now();return{schemaVersion:19,profile:{name:'사용자',theme:'midnight',fontScale:1,updatedAt:t},works:[],characters:[],intros:[],extras:[],guides:[],threads:[],memories:[],lorebooks:[],personas:[],widgetTemplates:[],presets:[],settings:{activeWorkId:null,activeCharacterId:null,activeThreadId:null,currentView:'home',defaultProvider:'google',defaultModel:'gemini-3.6-flash',memoryProvider:'google',memoryModel:'gemini-3.6-flash',temperature:.85,maxTokens:2500,recentMessageCount:24,memoryLimit:12,defaultDisplayMode:'novel'},appMeta:{},updatedAt:t}}
export function normalize(s){s=s&&typeof s==='object'?s:fresh();if(s.state&&typeof s.state==='object'&&!s.characters)s=s.state;const base=fresh();for(const k of ['works','characters','intros','extras','guides','threads','memories','lorebooks','personas','widgetTemplates','presets'])s[k]=arr(s[k]);s.profile={...base.profile,...(s.profile||{})};s.settings={...base.settings,...(s.settings||{})};s.appMeta={...(s.appMeta||{})};s.schemaVersion=Math.max(19,Number(s.schemaVersion||0));return s}
const stored=localStorage.getItem(STATE_KEY)||localStorage.getItem(LEGACY_KEY)||'null';export let state=normalize(JSON.parse(stored));export let revision=0;export let config=null;
export function setState(s){state=normalize(s);localStorage.setItem(STATE_KEY,JSON.stringify(state));}
export function work(id=state.settings.activeWorkId){return state.works.find(x=>x.id===id)||state.works.find(x=>!x.archived)||null}
export function char(id=state.settings.activeCharacterId){return state.characters.find(x=>x.id===id)||state.characters.find(x=>!x.archived)||null}
export function thread(id=state.settings.activeThreadId){return state.threads.find(x=>x.id===id)||null}
export function persona(th=thread()){return state.personas.find(x=>x.id===th?.personaId)||state.personas.find(x=>x.id===state.settings.activePersonaId)||state.personas[0]||null}
export function scoped(items,c=char(),w=work(c?.workId)){return arr(items).filter(x=>{if(x.enabled===false)return false;if(x.scopeType==='global')return true;if(x.scopeType==='character')return x.characterId===c?.id;return !x.workId||x.workId===w?.id||x.characterId===c?.id})}
export function memories(c=char(),th=thread()){return state.memories.filter(m=>m.characterId===c?.id&&m.status==='approved'&&m.enabled!==false&&(!m.threadId||m.threadId===th?.id)).sort((a,b)=>(b.pinned?1:0)-(a.pinned?1:0)||(b.importance||0)-(a.importance||0)).slice(0,th?.memorySettings?.limit||state.settings.memoryLimit||12)}
export function extras(c=char()){return scoped(state.extras,c).slice(0,30)}
export function presets(c=char()){return scoped(state.presets,c)}
export function guides(c=char()){return scoped(state.guides,c).sort((a,b)=>(b.priority||0)-(a.priority||0))}
export function lore(c=char()){return scoped(state.lorebooks,c).sort((a,b)=>(b.priority||0)-(a.priority||0)).slice(0,30)}
export function ensureDemoSeed(){if(state.appMeta?.mobileDemoSeed>=2)return false;const d=demoSeed,put=(key,item)=>{if(!state[key].some(x=>x.id===item.id))state[key].push(clone(item))};put('works',d.work);put('characters',d.character);put('personas',d.persona);put('intros',d.intro);d.extras.forEach(x=>put('extras',x));d.guides.forEach(x=>put('guides',x));d.lorebooks.forEach(x=>put('lorebooks',x));put('presets',d.preset);if(!state.settings.activeWorkId)state.settings.activeWorkId=d.work.id;if(!state.settings.activeCharacterId)state.settings.activeCharacterId=d.character.id;state.appMeta={...(state.appMeta||{}),mobileDemoSeed:2,mobileDemoSeedAt:now()};state.updatedAt=now();localStorage.setItem(STATE_KEY,JSON.stringify(state));return true}
export async function boot(){ensureDemoSeed();try{const b=await edge('bootstrap',{},BOOT_TIMEOUT);revision=Number(b.revision||0);config=b.config||{};if(b.state)setState(b.state);const changed=ensureDemoSeed();if(changed||!b.state)save(false).catch(console.warn);return{online:true}}catch(e){console.warn(e);ensureDemoSeed();return{online:false,error:e}}}
let timer;export function saveSoon(){state.updatedAt=now();localStorage.setItem(STATE_KEY,JSON.stringify(state));clearTimeout(timer);timer=setTimeout(()=>save(false).catch(console.warn),650)}
export async function save(force=false){state.updatedAt=now();localStorage.setItem(STATE_KEY,JSON.stringify(state));try{const r=await edge('sync-put',{revision,state});revision=Number(r.revision||revision);return r}catch(e){if(e.status===409){const r=await edge('sync-get');revision=Number(r.revision||revision);if(force){setState(r.state||state);throw new Error('다른 기기에서 저장된 내용이 있어 최신 상태를 불러왔어요. 다시 변경해 주세요.')}}throw e}}
export async function pull(){const r=await edge('sync-get');revision=Number(r.revision||0);if(r.state)setState(r.state);ensureDemoSeed();return state}
export function makeThread(c,intro=null,opt={}){const t=now(),preset=state.presets.find(x=>x.id===opt.presetId)||null,scene=intro?.scene||{date:'',time:'',location:'',state:''},th={id:uid('thread'),characterId:c.id,workId:c.workId||null,title:opt.title||intro?.threadTitle||intro?.title||`${c.name}과의 대화`,personaId:opt.personaId||intro?.recommendedPersonaId||state.personas.find(x=>x.workId===c.workId)?.id||state.personas[0]?.id||null,scene:clone(scene),messages:[],createdAt:t,updatedAt:t,currentSceneStartMessageId:null,lastMemoryExtractionMessageId:null,displayMode:opt.displayMode||state.settings.defaultDisplayMode||'novel',activePresetId:preset?.id||intro?.recommendedPresetId||null,provider:preset?.provider||c.defaultProvider||state.settings.defaultProvider,activeModel:preset?.model||c.defaultModel||state.settings.defaultModel,manualLoreIds:arr(opt.manualLoreIds||intro?.initialLoreIds),statusWidgets:clone(opt.statusWidgets||[]),statusWidgetState:{},memorySettings:{limit:state.settings.memoryLimit||12}};if(intro){const blocks=arr(intro.contentBlocks);if(blocks.length)for(const b of blocks){if(!b.content?.trim())continue;const who=b.speakerType==='player'||b.speaker==='player'?'user':'assistant';th.messages.push({id:uid('msg'),role:who,content:b.content,speakerType:b.speakerType||b.speaker||(who==='user'?'player':'character'),speakerId:b.speakerId||null,speakerName:b.speakerName||null,createdAt:t,provider:'intro',model:'intro'})}else if(intro.messages?.length)th.messages=intro.messages.map(m=>({...clone(m),id:uid('msg'),createdAt:t}));else if(intro.content)th.messages.push({id:uid('msg'),role:'assistant',content:intro.content,createdAt:t,provider:'intro',model:'intro'});}state.threads.unshift(th);state.settings.activeThreadId=th.id;state.settings.activeCharacterId=c.id;state.settings.activeWorkId=c.workId||state.settings.activeWorkId;saveSoon();return th}
export function exportState(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`LumiChat_backup_${new Date().toISOString().replace(/[:.]/g,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export async function importState(file){const raw=JSON.parse(await file.text());setState(raw.state||raw);ensureDemoSeed();await save(false);return state}
