const EDGE='https://vulpttgewjfkxojimyxl.supabase.co/functions/v1/lumichat-mobile';
const STATE_KEY='lumichat-mobile-state-v18';const DEV_KEY='lumichat-device-token-v1';
export const $=(q,r=document)=>r.querySelector(q);export const $$=(q,r=document)=>[...r.querySelectorAll(q)];
export const uid=(p='id')=>`${p}_${Date.now().toString(36)}_${crypto.randomUUID().slice(0,8)}`;
export const now=()=>new Date().toISOString();export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const clone=v=>JSON.parse(JSON.stringify(v));
function token(){let t=localStorage.getItem(DEV_KEY)||'';if(!/^[A-Za-z0-9_-]{32,160}$/.test(t)){const b=new Uint8Array(32);crypto.getRandomValues(b);t=btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');localStorage.setItem(DEV_KEY,t)}return t}
export async function edge(action,payload={}){let r;try{r=await fetch(EDGE,{method:'POST',headers:{'content-type':'application/json','x-lumichat-device':token()},body:JSON.stringify({action,...payload}),cache:'no-store'})}catch(e){throw new Error('모바일 서버에 연결하지 못했어요. 인터넷 연결을 확인해 주세요.')}let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.error||`요청 실패 (${r.status})`);e.status=r.status;e.code=d.code;e.data=d;throw e}return d}
export function fresh(){const t=now();return{schemaVersion:18,profile:{name:'사용자',theme:'midnight',fontScale:1,updatedAt:t},works:[],characters:[],intros:[],extras:[],guides:[],threads:[],memories:[],lorebooks:[],personas:[],widgetTemplates:[],presets:[],settings:{activeCharacterId:null,activeThreadId:null,currentView:'home',defaultProvider:'google',defaultModel:'gemini-3.6-flash',memoryProvider:'google',memoryModel:'gemini-3.6-flash',temperature:.85,maxTokens:2500,recentMessageCount:24,memoryLimit:12,defaultDisplayMode:'novel'},updatedAt:t}}
export function normalize(s){s=s&&typeof s==='object'?s:fresh();const base=fresh();for(const k of ['works','characters','intros','extras','guides','threads','memories','lorebooks','personas','widgetTemplates','presets'])if(!Array.isArray(s[k]))s[k]=[];s.profile={...base.profile,...(s.profile||{})};s.settings={...base.settings,...(s.settings||{})};s.schemaVersion=Math.max(18,Number(s.schemaVersion||0));return s}
export let state=normalize(JSON.parse(localStorage.getItem(STATE_KEY)||'null'));export let revision=0;export let config=null;
export function setState(s){state=normalize(s);localStorage.setItem(STATE_KEY,JSON.stringify(state));}
export function char(id=state.settings.activeCharacterId){return state.characters.find(x=>x.id===id)||state.characters[0]||null}
export function thread(id=state.settings.activeThreadId){return state.threads.find(x=>x.id===id)||null}
export function persona(){const th=thread();return state.personas.find(x=>x.id===th?.personaId)||state.personas[0]||null}
export function memories(c=char(),th=thread()){return state.memories.filter(m=>m.characterId===c?.id&&m.enabled!==false&&m.status!=='archived'&&(!m.threadId||m.threadId===th?.id)).sort((a,b)=>(b.pinned?1:0)-(a.pinned?1:0)||(b.importance||0)-(a.importance||0)).slice(0,state.settings.memoryLimit||12)}
export function lore(c=char()){return state.lorebooks.filter(x=>(!x.characterId||x.characterId===c?.id)&&x.enabled!==false).slice(0,20)}
export function extras(c=char()){return state.extras.filter(x=>!x.characterId||x.characterId===c?.id).slice(0,30)}
export async function boot(){const local=state;try{const b=await edge('bootstrap');revision=Number(b.revision||0);config=b.config||{};if(b.state)setState(b.state);else await save(true);return{online:true}}catch(e){console.warn(e);return{online:false,error:e}}}
let timer;export function saveSoon(){localStorage.setItem(STATE_KEY,JSON.stringify(state));clearTimeout(timer);timer=setTimeout(()=>save(false),650)}
export async function save(force=false){state.updatedAt=now();localStorage.setItem(STATE_KEY,JSON.stringify(state));try{const r=await edge('sync-put',{revision,state});revision=Number(r.revision||revision);return r}catch(e){if(e.status===409){const r=await edge('sync-get');revision=Number(r.revision||revision);if(force){setState(r.state||state);throw new Error('다른 기기에서 저장된 내용이 있어 최신 상태를 불러왔어요. 다시 변경해 주세요.')}}throw e}}
export async function pull(){const r=await edge('sync-get');revision=Number(r.revision||0);if(r.state)setState(r.state);return state}
export function makeThread(c,intro=null){const t=now(),th={id:uid('thread'),characterId:c.id,workId:c.workId||null,title:intro?.title||`${c.name}과의 대화`,personaId:state.personas[0]?.id||null,scene:intro?.scene||{date:'',time:'',location:'',state:''},messages:[],createdAt:t,updatedAt:t,currentSceneStartMessageId:null,lastMemoryExtractionMessageId:null,displayMode:state.settings.defaultDisplayMode||'novel'};if(intro){const blocks=Array.isArray(intro.contentBlocks)?intro.contentBlocks:[];if(blocks.length)for(const b of blocks){if(!b.content?.trim())continue;const who=b.speakerType==='player'?'user':'assistant';th.messages.push({id:uid('msg'),role:who,content:b.content,speakerId:b.speakerId||null,speakerName:b.speakerName||null,createdAt:t})}else if(intro.content)th.messages.push({id:uid('msg'),role:'assistant',content:intro.content,createdAt:t});}state.threads.unshift(th);state.settings.activeThreadId=th.id;state.settings.activeCharacterId=c.id;saveSoon();return th}
export function exportState(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`LumiChat_backup_${new Date().toISOString().replace(/[:.]/g,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export async function importState(file){const raw=JSON.parse(await file.text());setState(raw.state||raw);await save(false);return state}
