import{state,char,work,uid,now,saveSoon,esc,markDeleted,defaultSpeakerTextColor}from'./core.js';
const csv=s=>String(s||'').split(',').map(x=>x.trim()).filter(Boolean),val=(f,k,d='')=>f.elements[k]?.value?.trim?.()??d;
export const types={
 works:{label:'작품',icon:'▣',desc:'작품·세계관 묶음'},personas:{label:'유저 프로필',icon:'☺',desc:'대화에서 내가 맡는 인물'},extras:{label:'등장인물',icon:'♟',desc:'스토리 필요 시 자동 등장'},lorebooks:{label:'세계관·사건',icon:'◇',desc:'세계관과 사건 자료'},guides:{label:'출력 지침',icon:'✎',desc:'문체·정보 제한·주도권'},presets:{label:'응답 프리셋',icon:'⚡',desc:'모델·토큰·출력 지침'},widgetTemplates:{label:'내 위젯',icon:'▤',desc:'상태 위젯 템플릿'}
};
export function managerHomeHtml(){return Object.entries(types).map(([k,x])=>`<button data-manage-type="${k}"><b>${x.icon} ${x.label}</b><span>${x.desc} · ${state[k]?.length||0}</span></button>`).join('')}
const itemScope=x=>x.scopeType==='global'?'전체 공용':x.scopeType==='character'?'캐릭터 전용':'작품 공용';
export function listHtml(type){const cfg=types[type],c=char(),w=work(c?.workId);let items=(state[type]||[]).filter(x=>{if(type==='works')return !x.archived;if(x.scopeType==='global')return true;if(x.scopeType==='character')return !c||x.characterId===c.id;return !w||!x.workId||x.workId===w.id});return`<div class="sheet-form manager-sheet"><div class="manager-title"><div><h2>${cfg.icon} ${cfg.label}</h2><p>${cfg.desc}</p></div><button class="primary small" data-new-managed="${type}">＋ 추가</button></div>${items.length?`<div class="manager-bulk-bar"><label><input type="checkbox" id="managedSelectAll"> 전체</label><button class="soft" id="managedBulkClone">복제</button>${type==='extras'?'':'<button class="soft" id="managedBulkToggle">사용 전환</button>'}<button class="soft" id="managedBulkTags">태그 추가</button><button class="soft" id="managedBulkExport">선택 내보내기</button><button class="danger-soft" id="managedBulkDelete">삭제</button></div>`:''}<div class="manager-list">${items.map(x=>itemCard(type,x)).join('')||'<div class="empty mini-empty"><p>등록된 항목이 없어요.</p></div>'}</div><button data-close>닫기</button></div>`}
function itemCard(type,x){let title=x.title||x.name||'제목 없음',detail='';if(type==='works')detail=x.subtitle||x.description||'';else if(type==='personas')detail=x.relationship||x.description||x.background||'';else if(type==='extras')detail=[x.role,x.description].filter(Boolean).join(' · ');else if(type==='lorebooks')detail=`${x.collectionType==='event'?'사건':'세계관'} · ${x.content||''}`;else if(type==='guides')detail=x.content||'';else if(type==='presets')detail=`${x.provider||'기본'} · ${x.model||'기본 모델'} · ${x.maxTokens||''}t`;else detail=x.description||'';return`<article class="manage-item" data-managed-id="${esc(x.id)}"><label class="manage-select" aria-label="선택"><input type="checkbox" data-managed-select value="${esc(x.id)}"></label><div><small>${type==='works'?'':itemScope(x)}</small><b>${esc(title)}</b><p>${esc(detail).slice(0,180)}</p></div><div class="manage-actions"><button data-edit-managed="${type}" data-id="${esc(x.id)}">수정</button><button data-clone-managed="${type}" data-id="${esc(x.id)}">복제</button><button class="danger-soft" data-delete-managed="${type}" data-id="${esc(x.id)}">삭제</button></div></article>`}
function scopeFields(x={}){const c=char(),w=work(c?.workId);return`<div class="grid2"><label>적용 범위<select name="scopeType"><option value="work" ${x.scopeType!=='character'&&x.scopeType!=='global'?'selected':''}>작품 공용</option><option value="character" ${x.scopeType==='character'?'selected':''}>현재 캐릭터 전용</option><option value="global" ${x.scopeType==='global'?'selected':''}>전체 공용</option></select></label><label>현재 연결<span class="readonly-field">${esc(c?.name||w?.title||'없음')}</span></label></div>`}
export function editorHtml(type,item=null){const x=item||{},cfg=types[type];let body='';if(type==='works')body=`<label>작품명<input name="title" required value="${esc(x.title||'')}"></label><label>한 줄 소개<input name="subtitle" value="${esc(x.subtitle||'')}"></label><label>작품 설명<textarea name="description" rows="6">${esc(x.description||'')}</textarea></label><label>태그<input name="tags" value="${esc((x.tags||[]).join(', '))}"></label><label>커버 이미지 URL / Data URL<input name="cover" value="${esc(x.cover||'')}"></label><label class="check"><input type="checkbox" name="favorite" ${x.favorite?'checked':''}> 즐겨찾기</label>`;
if(type==='personas')body=`${scopeFields(x)}<label>프로필 이름<input name="name" required value="${esc(x.name||'')}"></label><label>별칭<input name="aliases" value="${esc(x.aliases||'')}"></label><label>프로필 이미지 URL / Data URL<input name="avatar" value="${esc(x.avatar||'')}"></label><label>대사 글씨색<input name="dialogueTextColor" type="color" value="${esc(x.dialogueTextColor||defaultSpeakerTextColor('pc',x.id||x.name||'user'))}"><small class="hint">이 유저 프로필의 기본 대사색</small></label><label>외모<textarea name="appearance">${esc(x.appearance||'')}</textarea></label><label>성격<textarea name="personality">${esc(x.personality||'')}</textarea></label><label>말투<textarea name="speech">${esc(x.speech||'')}</textarea></label><label>배경<textarea name="background">${esc(x.background||x.description||'')}</textarea></label><label>현재 관계<textarea name="relationship">${esc(x.relationship||'')}</textarea></label><label>현재 상태<textarea name="currentState">${esc(x.currentState||'')}</textarea></label><div class="grid2"><label>알고 있는 사실<textarea name="knownFacts">${esc(x.knownFacts||'')}</textarea></label><label>숨기는 사실<textarea name="hiddenFacts">${esc(x.hiddenFacts||'')}</textarea></label></div><label>사용자 주도권 규칙<textarea name="agencyRules">${esc(x.agencyRules||'')}</textarea></label><div class="grid2"><label>AI 참조<select name="readPolicy"><option value="required" ${(x.readPolicy||'required')==='required'?'selected':''}>필수</option><option value="auto" ${x.readPolicy==='auto'?'selected':''}>자동</option><option value="keyword" ${x.readPolicy==='keyword'?'selected':''}>키워드</option><option value="manual" ${x.readPolicy==='manual'?'selected':''}>수동</option></select></label><label>호출 키워드<input name="keywords" value="${esc((x.triggerKeywords||[]).join(', '))}"></label></div>`;
if(type==='extras')body=`${scopeFields(x)}<label>이름<input name="name" required value="${esc(x.name||'')}"></label><label>역할<input name="role" value="${esc(x.role||'')}"></label><label>대사 글씨색<input name="dialogueTextColor" type="color" value="${esc(x.dialogueTextColor||defaultSpeakerTextColor('extra',`extra:${x.id||x.name||'new'}`))}"><small class="hint">이 등장인물의 기본 대사색</small></label><label>외형·성격·설정<textarea name="description" rows="6">${esc(x.description||'')}</textarea></label><label>말투·호칭<textarea name="speech">${esc(x.speech||'')}</textarea></label><label>관계<textarea name="relationships">${esc(x.relationships||'')}</textarea></label><div class="grid2"><label>알고 있는 사실<textarea name="knownFacts">${esc(x.knownFacts||'')}</textarea></label><label>모르는 사실<textarea name="unknownFacts">${esc(x.unknownFacts||'')}</textarea></label></div>`;
if(type==='lorebooks')body=`${scopeFields(x)}<div class="grid2"><label>분류<select name="collectionType"><option value="world" ${x.collectionType!=='event'?'selected':''}>세계관</option><option value="event" ${x.collectionType==='event'?'selected':''}>사건</option></select></label><label>AI 참조<select name="readPolicy"><option value="required" ${(x.readPolicy||x.mode)==='required'||x.mode==='always'?'selected':''}>필수</option><option value="auto" ${(!x.readPolicy&&x.mode!=='always'&&x.mode!=='manual'&&x.mode!=='keyword')||x.readPolicy==='auto'?'selected':''}>자동</option><option value="keyword" ${(x.readPolicy||x.mode)==='keyword'?'selected':''}>키워드</option><option value="manual" ${(x.readPolicy||x.mode)==='manual'?'selected':''}>수동</option></select></label></div><label>제목<input name="title" required value="${esc(x.title||'')}"></label><label>내용<textarea name="content" rows="9">${esc(x.content||'')}</textarea></label><label>호출 키워드<input name="keywords" value="${esc((x.triggerKeywords||x.keywords||[]).join(', '))}"></label><label>우선순위<input name="priority" type="number" min="1" max="10" value="${x.priority||5}"></label><label class="check"><input type="checkbox" name="enabled" ${x.enabled!==false?'checked':''}> 사용</label>`;
if(type==='guides')body=`${scopeFields(x)}<div class="grid2"><label>우선순위<input name="priority" type="number" min="1" max="10" value="${x.priority||5}"></label><label>AI 참조<select name="readPolicy"><option value="required" ${x.readPolicy!=='auto'&&x.readPolicy!=='keyword'&&x.readPolicy!=='manual'?'selected':''}>필수</option><option value="auto" ${x.readPolicy==='auto'?'selected':''}>자동</option><option value="keyword" ${x.readPolicy==='keyword'?'selected':''}>키워드</option><option value="manual" ${x.readPolicy==='manual'?'selected':''}>수동</option></select></label></div><label>호출 키워드<input name="keywords" value="${esc((x.triggerKeywords||[]).join(', '))}"></label><label>제목<input name="title" required value="${esc(x.title||'')}"></label><label>지침 내용<textarea name="content" rows="10">${esc(x.content||'')}</textarea></label><label class="check"><input type="checkbox" name="enabled" ${x.enabled!==false?'checked':''}> 적용</label>`;
if(type==='presets')body=`${scopeFields(x)}<label>프리셋 이름<input name="name" required value="${esc(x.name||'')}"></label><div class="grid2"><label>Provider<select name="provider"><option value="">앱 기본값</option>${['google','openai','anthropic','openrouter','custom'].map(p=>`<option value="${p}" ${x.provider===p?'selected':''}>${p}</option>`).join('')}</select></label><label>Model<input name="model" value="${esc(x.model||'')}"></label></div><div class="grid2"><label>Temperature<input name="temperature" type="number" min="0" max="2" step="0.05" value="${x.temperature??.85}"></label><label>최대 토큰<input name="maxTokens" type="number" min="256" max="65536" value="${x.maxTokens||2500}"></label></div><label>추가 지침<textarea name="instructions" rows="8">${esc(x.instructions||'')}</textarea></label>`;
if(type==='widgetTemplates')body=`<label>위젯 이름<input name="title" required value="${esc(x.title||'')}"></label><label>설명<input name="description" value="${esc(x.description||'')}"></label><label>상태값 정의<textarea name="fields" rows="8" placeholder="키 :: AI에게 전달할 지시\n한 줄에 하나">${esc((x.fields||[]).map(f=>`${f.key} :: ${f.instruction||''}`).join('\n'))}</textarea></label><label>HTML 템플릿<textarea name="template" rows="12" placeholder="{{키}}와 {{user}}, {{char}} 사용">${esc(x.template||'<div>{{상태}}</div>')}</textarea></label><div class="grid2"><label>크기<select name="size"><option value="wide" ${x.display?.size!=='compact'?'selected':''}>wide</option><option value="compact" ${x.display?.size==='compact'?'selected':''}>compact</option></select></label><label>높이<input name="height" type="number" min="100" max="1600" value="${x.display?.height||360}"></label></div>`;
return`<form id="managedForm" class="sheet-form" data-manage-type="${type}"><input type="hidden" name="id" value="${esc(x.id||'')}"><h2>${item?'수정':'추가'} · ${cfg.label}</h2>${body}<div class="sheet-actions"><button type="button" data-close>취소</button><button class="primary">저장</button></div></form>`}
function scopeData(f){const c=char(),w=work(c?.workId),scope=val(f,'scopeType','work');return{scopeType:scope,workId:scope==='global'?null:(w?.id||c?.workId||null),characterId:scope==='character'?c?.id:null}}
export function saveManaged(type,f){const id=val(f,'id')||uid(type.slice(0,-1)),old=state[type].find(x=>x.id===id)||{},t=now();let x={...old,id,createdAt:old.createdAt||t,updatedAt:t};if(type==='works')x={...x,title:val(f,'title'),subtitle:val(f,'subtitle'),description:val(f,'description'),tags:csv(val(f,'tags')),cover:val(f,'cover'),favorite:f.elements.favorite.checked,archived:false};
if(type==='personas')x={...x,...scopeData(f),name:val(f,'name'),aliases:val(f,'aliases'),avatar:val(f,'avatar'),dialogueTextColor:val(f,'dialogueTextColor')||old.dialogueTextColor||defaultSpeakerTextColor('pc',id),appearance:val(f,'appearance'),personality:val(f,'personality'),speech:val(f,'speech'),background:val(f,'background'),relationship:val(f,'relationship'),currentState:val(f,'currentState'),knownFacts:val(f,'knownFacts'),hiddenFacts:val(f,'hiddenFacts'),agencyRules:val(f,'agencyRules'),readPolicy:val(f,'readPolicy','required'),triggerKeywords:csv(val(f,'keywords'))};
if(type==='extras')x={...x,...scopeData(f),name:val(f,'name'),role:val(f,'role'),dialogueTextColor:val(f,'dialogueTextColor')||old.dialogueTextColor||defaultSpeakerTextColor('extra',`extra:${id}`),description:val(f,'description'),speech:val(f,'speech'),relationships:val(f,'relationships'),knownFacts:val(f,'knownFacts'),unknownFacts:val(f,'unknownFacts'),enabled:true};
if(type==='lorebooks')x={...x,...scopeData(f),collectionType:val(f,'collectionType','world'),title:val(f,'title'),content:val(f,'content'),readPolicy:val(f,'readPolicy','auto'),mode:val(f,'readPolicy','auto'),triggerKeywords:csv(val(f,'keywords')),keywords:csv(val(f,'keywords')),priority:Number(val(f,'priority','5')),enabled:f.elements.enabled.checked};
if(type==='guides')x={...x,...scopeData(f),title:val(f,'title'),content:val(f,'content'),readPolicy:val(f,'readPolicy','required'),triggerKeywords:csv(val(f,'keywords')),priority:Number(val(f,'priority','5')),enabled:f.elements.enabled.checked};
if(type==='presets')x={...x,...scopeData(f),name:val(f,'name'),provider:val(f,'provider'),model:val(f,'model'),temperature:Number(val(f,'temperature','.85')),maxTokens:Number(val(f,'maxTokens','2500')),instructions:val(f,'instructions')};
if(type==='widgetTemplates'){const fields=val(f,'fields').split(/\n/).map(line=>{const [key,...rest]=line.split('::');return{key:key?.trim(),instruction:rest.join('::').trim()}}).filter(x=>x.key),history=Array.isArray(old.versionHistory)?[...old.versionHistory]:[];if(old.id&&old.template&&old.template!==val(f,'template'))history.unshift({id:uid('widgetver'),savedAt:t,title:old.title||'',description:old.description||'',fields:JSON.parse(JSON.stringify(old.fields||[])),template:old.template,display:JSON.parse(JSON.stringify(old.display||{}))});x={...x,title:val(f,'title'),description:val(f,'description'),fields,template:val(f,'template'),display:{size:val(f,'size','wide'),height:Number(val(f,'height','360'))},versionHistory:history.slice(0,30),enabled:true}}
const i=state[type].findIndex(y=>y.id===id);if(i>=0)state[type][i]=x;else state[type].push(x);if(type==='works'){state.settings.activeWorkId=x.id;const c=state.characters.find(z=>z.workId===x.id);if(c)state.settings.activeCharacterId=c.id}saveSoon();return x}
export function deleteManaged(type,id){
  if(type==='works'){
    const x=state.works.find(y=>y.id===id);if(x){x.archived=true;x.updatedAt=now()}
    saveSoon();return
  }
  const current=(state[type]||[]).find(x=>x.id===id);if(!current)return;
  const meta={label:types[type]?.label||'항목'};
  if(type==='personas'){meta.threadRefs=state.threads.filter(th=>th.personaId===id).map(th=>th.id);meta.introRefs=state.intros.filter(ep=>ep.recommendedPersonaId===id).map(ep=>ep.id)}
  if(type==='presets'){meta.threadRefs=state.threads.filter(th=>th.activePresetId===id).map(th=>th.id);meta.introRefs=state.intros.filter(ep=>ep.recommendedPresetId===id).map(ep=>ep.id)}
  if(type==='lorebooks'){meta.threadRefs=state.threads.filter(th=>(th.manualLoreIds||[]).includes(id)).map(th=>th.id);meta.introRefs=state.intros.filter(ep=>(ep.initialLoreIds||[]).includes(id)).map(ep=>ep.id)}
  if(type==='guides'){meta.threadRefs=state.threads.filter(th=>(th.manualGuideIds||[]).includes(id)).map(th=>th.id);meta.introRefs=state.intros.filter(ep=>(ep.initialGuideIds||[]).includes(id)).map(ep=>ep.id)}
  if(type==='extras'){meta.threadRefs=state.threads.filter(th=>(th.activeExtraIds||[]).includes(id)).map(th=>th.id);meta.introRefs=state.intros.filter(ep=>(ep.initialExtraIds||[]).includes(id)).map(ep=>ep.id)}
  if(type==='widgetTemplates'){meta.threadWidgetRefs=[];meta.characterWidgetRefs=[];for(const th of state.threads)for(const w of th.statusWidgets||[])if(w.libraryTemplateId===id)meta.threadWidgetRefs.push({threadId:th.id,widgetId:w.id});for(const c of state.characters)for(const w of c.defaultStatusWidgets||[])if(w.libraryTemplateId===id)meta.characterWidgetRefs.push({characterId:c.id,widgetId:w.id})}
  state.settings.trash=Array.isArray(state.settings.trash)?state.settings.trash:[];state.settings.trash.unshift({id:uid('trash'),key:type,item:JSON.parse(JSON.stringify(current)),deletedAt:now(),meta});state.settings.trash=state.settings.trash.slice(0,500);
  markDeleted(type,id);state[type]=(state[type]||[]).filter(x=>x.id!==id);
  if(type==='personas'){
    const fallbackFor=th=>state.personas.find(p=>p.id!==id&&(p.scopeType==='global'||p.workId===th.workId||p.characterId===th.characterId))||state.personas.find(p=>p.id!==id)||null;
    for(const th of state.threads)if(th.personaId===id)th.personaId=fallbackFor(th)?.id||null;
    for(const intro of state.intros)if(intro.recommendedPersonaId===id)intro.recommendedPersonaId=null;
    if(state.settings.activePersonaId===id)state.settings.activePersonaId=state.personas[0]?.id||null;
  }
  if(type==='presets'){for(const th of state.threads)if(th.activePresetId===id)th.activePresetId=null;for(const intro of state.intros)if(intro.recommendedPresetId===id)intro.recommendedPresetId=null}
  if(type==='lorebooks'){
    for(const th of state.threads){th.manualLoreIds=(th.manualLoreIds||[]).filter(x=>x!==id);th.pendingEventLoreIds=(th.pendingEventLoreIds||[]).filter(x=>x!==id)}
    for(const intro of state.intros)intro.initialLoreIds=(intro.initialLoreIds||[]).filter(x=>x!==id);
  }
  if(type==='guides'){for(const th of state.threads)th.manualGuideIds=(th.manualGuideIds||[]).filter(x=>x!==id);for(const intro of state.intros)intro.initialGuideIds=(intro.initialGuideIds||[]).filter(x=>x!==id)}
  if(type==='extras'){
    for(const th of state.threads)if(Array.isArray(th.activeExtraIds))th.activeExtraIds=th.activeExtraIds.filter(x=>x!==id);
    for(const intro of state.intros)intro.initialExtraIds=(intro.initialExtraIds||[]).filter(x=>x!==id);
  }
  if(type==='widgetTemplates'){
    for(const th of state.threads)for(const w of th.statusWidgets||[])if(w.libraryTemplateId===id)w.libraryTemplateId=null;
    for(const c of state.characters)for(const w of c.defaultStatusWidgets||[])if(w.libraryTemplateId===id)w.libraryTemplateId=null;
  }
  saveSoon()
}
