import{$,$$,state,char,saveSoon}from'./core.js';
import{episodeInline,saveEpisodeRoot,addSpeakerBlock}from'./editors.js';
import{builtInWidgets,widgetCopy}from'./widgets.js';
const done=new WeakSet();
function activeCharacter(form){const id=form?.elements?.id?.value;return state.characters.find(x=>x.id===id)||char()}
function migrateLedger(){const stock=builtInWidgets.find(w=>w.id==='builtin-user-ledger-v1');if(!stock)return;let changed=false;for(const th of state.threads||[]){th.statusWidgets=(th.statusWidgets||[]).map(w=>{const ledger=[w.id,w.presetId,w.libraryTemplateId].includes('builtin-user-ledger-v1');if(!ledger)return w;const old=(w.fields||[]).some(f=>['캐릭터시선','사용자시선','끄적1','끄적2'].includes(f.key))||!(w.fields||[]).some(f=>f.key==='스킨십진도');if(!old)return w;changed=true;return{...widgetCopy(stock),id:w.id,presetId:w.presetId||'builtin-user-ledger-v1',enabled:w.enabled!==false}});for(const w of th.statusWidgets||[]){if(w.presetId!=='builtin-user-ledger-v1'&&w.id!=='builtin-user-ledger-v1')continue;const v=th.statusWidgetState?.[w.id]?.values;if(!v)continue;if(v.캐릭터시선&&!v.캐릭터감상)v.캐릭터감상=v.캐릭터시선;if(v.사용자시선&&!v.사용자감상)v.사용자감상=v.사용자시선;if(v.끄적1&&!v.끄적질문){v.끄적질문자=state.characters.find(x=>x.id===th.characterId)?.name||'캐릭터';v.끄적질문=v.끄적1}if(v.끄적2&&!v.끄적답변){v.끄적답변자=state.personas.find(x=>x.id===th.personaId)?.name||state.profile.name||'사용자';v.끄적답변=v.끄적2}delete v.캐릭터시선;delete v.사용자시선;delete v.끄적1;delete v.끄적2}}
if(changed)saveSoon()}
function wireInline(form){if(!form||done.has(form))return;done.add(form);const c=activeCharacter(form);let selected=c?.id?state.intros.find(x=>x.characterId===c.id)?.id||null:null;
 const episodeTab=form.querySelector('[data-tab="episode"]');
 function activate(){form.querySelectorAll('.form-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab==='episode'));form.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!=='episode');render()}
 episodeTab?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();activate()},true);
 function wireHost(host,ep){const del=()=>host.querySelectorAll('.speaker-delete').forEach(b=>b.onclick=()=>{const rows=host.querySelectorAll('.speaker-block');if(rows.length>1)b.closest('.speaker-block').remove();else b.closest('.speaker-block').querySelector('.speaker-content').value=''});del();host.querySelector('.addSpeakerBlock')?.addEventListener('click',()=>{addSpeakerBlock(host.querySelector('.speakerBlocks'),c);del()});host.querySelector('.inlineEpisodeSave')?.addEventListener('click',()=>{const saved=saveEpisodeRoot(host,ep,c);selected=saved.id;render()});host.querySelector('.inlineEpisodeDelete')?.addEventListener('click',e=>{const b=e.currentTarget;if(!ep?.id)return;if(b.dataset.armed!=='1'){b.dataset.armed='1';b.textContent='한 번 더 눌러 삭제';setTimeout(()=>{if(b.isConnected){b.dataset.armed='0';b.textContent='삭제'}},2500);return}state.intros=state.intros.filter(x=>x.id!==ep.id);if(c.defaultIntroId===ep.id)c.defaultIntroId=state.intros.find(x=>x.characterId===c.id)?.id||null;selected=state.intros.find(x=>x.characterId===c.id)?.id||null;saveSoon();render()})}
 function render(){const list=form.querySelector('#episodeMiniList'),host=form.querySelector('#episodeInlineHost');if(!list||!host)return;if(!c?.id){list.innerHTML='<p class="hint">캐릭터 기본 정보를 저장한 뒤 같은 편집기의 에피소드 탭에서 이어서 편집할 수 있어요.</p>';host.innerHTML='';return}const eps=state.intros.filter(x=>x.characterId===c.id);if(!selected&&eps.length)selected=eps[0].id;list.innerHTML=eps.length?eps.map(x=>`<button type="button" class="episode-choice ${x.id===selected?'active':''}" data-v157-ep="${x.id}"><b>${x.title||'에피소드'}</b><span>${x.scene?.location||x.scene?.state||'인트로 설정'}</span></button>`).join(''):'<p class="hint">에피소드가 없어요. 아래 ＋ 버튼으로 바로 추가할 수 있어요.</p>';list.querySelectorAll('[data-v157-ep]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();selected=b.dataset.v157Ep;render()},true));const ep=state.intros.find(x=>x.id===selected)||null;host.innerHTML=episodeInline(ep,c);wireHost(host,ep)}
 form.querySelector('#addEpisodeMini')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();if(!c?.id)return;selected=null;const host=form.querySelector('#episodeInlineHost');host.innerHTML=episodeInline(null,c);wireHost(host,null)},true);
 if(!form.querySelector('#episodeInlineHost')){const panel=form.querySelector('[data-panel="episode"]');panel?.insertAdjacentHTML('beforeend','<div id="episodeInlineHost" class="episode-inline-host"></div>')}
}
function sweep(){document.querySelectorAll('[id="episodes"]').forEach(x=>x.remove());document.querySelectorAll('.page-head small').forEach(x=>{if(x.textContent.includes('LUMICHAT MOBILE'))x.textContent='LUMICHAT MOBILE · v0.15.7'});wireInline(document.querySelector('#charForm'))}
new MutationObserver(sweep).observe(document.documentElement,{childList:true,subtree:true});migrateLedger();sweep();
