const VERSION='v0.15.13';
function makeSwitch(labelText,id){const label=document.createElement('label');label.className='expert-switch';label.innerHTML=`<input id="${id}" type="checkbox"><span class="switch-ui"></span><span>${labelText}</span>`;return label}
function patchCreator(form){if(!form||form.dataset.v01513Patched)return;form.dataset.v01513Patched='1';form.classList.add('creator-form');const title=form.querySelector(':scope>h2');if(title&&!form.querySelector('.creator-head')){const head=document.createElement('header');head.className='creator-head';const back=document.createElement('button');back.type='button';back.className='creator-back';back.setAttribute('data-close','');back.setAttribute('aria-label','닫기');back.textContent='‹';head.append(back,title);const expert=makeSwitch('전문가 모드','creatorExpertMode');head.append(expert);form.prepend(head);const cb=expert.querySelector('input');cb.addEventListener('change',()=>form.classList.toggle('expert',cb.checked))}form.querySelector('.form-tabs')?.classList.add('five')}
function plainFromBlocks(root){return[...root.querySelectorAll('.speaker-content')].map(x=>x.value.trim()).filter(Boolean).join('\n\n')}
function patchEpisode(root){if(!root||root.dataset.v01513Mode)return;root.dataset.v01513Mode='split';const blocks=root.querySelector('.speakerBlocks');if(!blocks)return;const host=blocks.parentElement,controls=document.createElement('div'),plain=document.createElement('div');host.classList.add('episode-content');controls.className='episode-mode-tabs';controls.innerHTML='<button type="button" data-v01513-mode="plain">줄글</button><button type="button" data-v01513-mode="split" class="active">나눠쓰기</button>';plain.className='episode-plain-panel';plain.hidden=true;plain.innerHTML='<textarea class="episode-plain-content" rows="12" placeholder="에피소드의 시작 내용을 한 번에 작성해 주세요."></textarea>';host.insertBefore(controls,blocks);host.insertBefore(plain,blocks);const buttons=[...controls.querySelectorAll('button')],area=plain.querySelector('textarea');const setMode=mode=>{root.dataset.v01513Mode=mode;buttons.forEach(b=>b.classList.toggle('active',b.dataset.v01513Mode===mode));plain.hidden=mode!=='plain';blocks.hidden=mode==='plain';const add=root.querySelector('.addSpeakerBlock');if(add)add.hidden=mode==='plain';if(mode==='plain'&&!area.value.trim())area.value=plainFromBlocks(root)};buttons.forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.v01513Mode)));root.addEventListener('click',e=>{if(!e.target.closest('.inlineEpisodeSave')||root.dataset.v01513Mode!=='plain')return;const rows=[...root.querySelectorAll('.speaker-block')];if(!rows.length)return;rows.slice(1).forEach(r=>r.remove());const row=rows[0],sel=row.querySelector('.speaker-kind'),ta=row.querySelector('.speaker-content');if(sel)sel.value='narration';if(ta)ta.value=area.value},true)}
function storyMarkup(text,user=false){const div=document.createElement('div');const parts=String(text||'').split(/\n{2,}/).map(x=>x.trim()).filter(Boolean);for(const part of parts){const p=document.createElement('p');p.className=user?'mobile-user-line':(/^[“"「『]/.test(part)?'mobile-dialogue':'mobile-narration');p.textContent=part.replace(/^\*([\s\S]*)\*$/,'$1');div.append(p)}return div.innerHTML}
function patchChat(){document.querySelectorAll('.msg').forEach(msg=>{if(msg.dataset.v01513Chat)return;msg.dataset.v01513Chat='1';const body=msg.querySelector('.msg-body');if(body){const text=body.innerText||body.textContent||'';body.innerHTML=storyMarkup(text,msg.classList.contains('user'))}const head=msg.querySelector(':scope>header');if(head&&msg.classList.contains('assistant')){const time=head.querySelector('span');if(time)time.hidden=true}})}
function normalize(){document.title=document.title.replace(/v0\.15\.\d+/g,VERSION);document.querySelectorAll('.page-head small').forEach(el=>el.textContent=el.textContent.replace(/v0\.15\.\d+/g,VERSION));document.querySelectorAll('button').forEach(b=>{const t=(b.textContent||'').trim();if(t==='캐릭터 편집')b.textContent='편집';if(t==='에피소드 편집'||t==='소개 편집')b.hidden=true})}
function patchAll(){normalize();patchCreator(document.querySelector('#charForm'));document.querySelectorAll('.episode-inline-form').forEach(patchEpisode);patchChat()}
const observer=new MutationObserver(patchAll);observer.observe(document.documentElement,{subtree:true,childList:true});patchAll();