export const TRASH_DAYS=30;
const norm=s=>String(s??'').toLowerCase().replace(/\s+/g,' ').trim();
export function searchThreadMessages(thread,term){const q=norm(term);if(!q)return[];return (thread?.messages||[]).map((m,index)=>({m,index,text:String(m.content||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()})).filter(x=>norm(x.text).includes(q));}
function rgb(hex){const m=String(hex||'').match(/^#([0-9a-f]{6})$/i);if(!m)return null;const n=parseInt(m[1],16);return[(n>>16)&255,(n>>8)&255,n&255]}
const lin=n=>{n/=255;return n<=.03928?n/12.92:((n+.055)/1.055)**2.4};
export function contrastRatio(fg,bg){const a=rgb(fg),b=rgb(bg);if(!a||!b)return 0;const x=.2126*lin(a[0])+.7152*lin(a[1])+.0722*lin(a[2]),y=.2126*lin(b[0])+.7152*lin(b[1])+.0722*lin(b[2]);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)}
export function safeTextColor(bg,preferred='#ffffff'){if(contrastRatio(preferred,bg)>=4.5)return preferred;return contrastRatio('#fff',bg)>=contrastRatio('#111111',bg)?'#ffffff':'#111111'}
export function addTrash(state,key,item,label,meta={}){state.settings.trash=Array.isArray(state.settings.trash)?state.settings.trash:[];const entry={id:`trash_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,key,item:JSON.parse(JSON.stringify(item)),deletedAt:new Date().toISOString(),meta:{label,...meta}};state.settings.trash.unshift(entry);state.settings.trash=state.settings.trash.filter(x=>Date.now()-new Date(x.deletedAt).getTime()<TRASH_DAYS*86400000).slice(0,500);return entry}
export function restoreTrash(state,entry){if(!entry?.item||!Array.isArray(state[entry.key]))return false;if(!state[entry.key].some(x=>x.id===entry.item.id))state[entry.key].push(JSON.parse(JSON.stringify(entry.item)));state.settings.trash=(state.settings.trash||[]).filter(x=>x.id!==entry.id);state.settings.deletedItems=(state.settings.deletedItems||[]).filter(x=>!(x.key===entry.key&&x.id===entry.item.id));return true}
export function trashDaysLeft(entry){return Math.max(0,Math.ceil((TRASH_DAYS*86400000-(Date.now()-new Date(entry.deletedAt).getTime()))/86400000))}
export function sceneTimeline(thread){const out=[],seen=new Set();for(const [index,m] of (thread?.messages||[]).entries()){const s=m.sceneSnapshot||{};const key=[s.date,s.time,s.location,s.state].join('|');if(!key.replaceAll('|','').trim()||seen.has(key))continue;seen.add(key);out.push({messageId:m.id,index,scene:s})}return out}
export function branchRows(state,thread){if(!thread)return[];const threads=(state.threads||[]).filter(t=>t.characterId===thread.characterId),parentOf=t=>t?.branchedFrom?.threadId||t?.parentThreadId||null;let root=thread,seen=new Set();while(parentOf(root)&&!seen.has(root.id)){seen.add(root.id);root=threads.find(t=>t.id===parentOf(root))||root;if(!parentOf(root))break}const byParent=new Map();for(const t of threads){const p=parentOf(t)||'';if(!byParent.has(p))byParent.set(p,[]);byParent.get(p).push(t)}const out=[];const walk=(t,depth=0)=>{out.push({id:t.id,title:t.title,parentThreadId:parentOf(t),messageId:t.branchedFrom?.messageId||t.branchFromMessageId||null,depth,active:t.id===thread.id});for(const child of byParent.get(t.id)||[])if(child.id!==t.id)walk(child,depth+1)};walk(root,0);return out;}
export function memorySimilarity(a,b){const wa=new Set(norm(`${a?.title||''} ${a?.content||''}`).split(/[^\p{L}\p{N}_]+/u).filter(x=>x.length>1)),wb=new Set(norm(`${b?.title||''} ${b?.content||''}`).split(/[^\p{L}\p{N}_]+/u).filter(x=>x.length>1));if(!wa.size||!wb.size)return 0;let hit=0;for(const x of wa)if(wb.has(x))hit++;return hit/Math.max(wa.size,wb.size)}
export function detectMemoryConflict(candidate,existing=[]){return existing.map(x=>({item:x,similarity:memorySimilarity(candidate,x)})).filter(x=>x.similarity>=.45).sort((a,b)=>b.similarity-a.similarity).slice(0,5)}

const VOID_TAGS=new Set(['area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr']);
export function validateHtmlStructure(html=''){const errors=[],stack=[],src=String(html||''),re=/<!--[\s\S]*?-->|<!DOCTYPE[^>]*>|<\/?[A-Za-z][^>]*>/gi;let m;while((m=re.exec(src))){const token=m[0];if(token.startsWith('<!--')||/^<!doctype/i.test(token))continue;const close=/^<\//.test(token),name=(token.match(/^<\/?\s*([A-Za-z0-9:-]+)/)||[])[1]?.toLowerCase();if(!name)continue;if(close){if(VOID_TAGS.has(name)){errors.push(`닫을 수 없는 <${name}> 태그에 종료 태그가 있어요.`);continue}const top=stack.at(-1);if(top===name){stack.pop();continue}const at=stack.lastIndexOf(name);if(at<0){errors.push(`여는 태그가 없는 </${name}>가 있어요.`);continue}errors.push(`<${stack.slice(at+1).join('> 안의 <')}> 태그가 닫히기 전에 </${name}>가 나왔어요.`);stack.splice(at,1)}else if(!VOID_TAGS.has(name)&&!/\/\s*>$/.test(token))stack.push(name)}if(stack.length)errors.push(`닫히지 않은 태그: ${stack.slice(-8).map(x=>`<${x}>`).join(', ')}`);return{ok:!errors.length,errors}}
export function validateWidgetTemplate(widget){const errors=[],warnings=[],fields=new Set((widget?.fields||[]).map(f=>String(f.key||'').trim()).filter(Boolean)),tpl=String(widget?.template||widget?.html||''),used=new Set([...tpl.matchAll(/{{\s*([^{}]+?)\s*}}/g)].map(m=>m[1].trim()).filter(x=>!['user','char','thread','character','conversation','scene','scene_date','scene_time','scene_location'].includes(x)));for(const k of used)if(!fields.has(k))warnings.push(`정의되지 않은 상태값: ${k}`);for(const k of fields)if(!used.has(k))warnings.push(`HTML에서 사용하지 않는 상태값: ${k}`);if(!tpl.trim())errors.push('HTML 템플릿이 비어 있어요.');const ids=[...(widget?.fields||[])].map(x=>String(x.key||'').trim()).filter(Boolean);if(new Set(ids).size!==ids.length)errors.push('상태값 키가 중복돼요.');errors.push(...validateHtmlStructure(tpl).errors);return{errors:[...new Set(errors)],warnings:[...new Set(warnings)],ok:errors.length===0}}
export function introBlocksHtml(blocks=[]){const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));return(blocks||[]).map(b=>{const t=b.type||'text',text=e(b.text||'').replace(/\n/g,'<br>');if(t==='heading')return`<h2>${text}</h2>`;if(t==='image')return`<figure><img src="${e(b.src||'')}" alt="">${b.caption?`<figcaption>${e(b.caption)}</figcaption>`:''}</figure>`;if(t==='quote')return`<blockquote>${text}</blockquote>`;if(t==='divider')return'<hr>';if(t==='profile')return`<section class="intro-profile-block"><b>${e(b.title||'프로필')}</b><p>${text}</p></section>`;if(t==='card')return`<section class="intro-card-block"><b>${e(b.title||'카드')}</b><p>${text}</p></section>`;if(t==='button')return`<a class="intro-button-block" href="${e(b.href||'#')}" target="_blank" rel="noopener noreferrer">${e(b.label||b.text||'바로가기')}</a>`;return`<p>${text}</p>`}).join('')}
