const CLOUD_API='https://vulpttgewjfkxojimyxl.supabase.co/functions/v1/devlib-mobile';
const POLL_MS=15000;
const QUEUE_KEY='devlib_mobile_pending_v25';
let currentData=null,lastSignature='',loading=false,mode='readonly',editingId='',editingBase=null,creating=false,conflictAction=null;

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=v=>Array.isArray(v)?v:[];
const fmt=v=>{if(!v)return'기록 없음';const d=new Date(Number(v)||v);if(isNaN(d))return'기록 없음';return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)};
const clock=()=>new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const AZ=[['overview','1. 프로젝트 개요 · 목적'],['goals','2. 최종 목표 · 완성 기준'],['scope','3. 범위 · 포함/제외'],['architecture','4. 구조 · 아키텍처'],['features','5. 기능 명세'],['ui','6. UI · UX · 디자인'],['data','7. 데이터 · 저장 · 상태'],['workflow','8. 사용자 흐름 · 동작 규칙'],['sync','9. 자동화 · 동기화'],['integration','10. 외부 연동 · API'],['mobile','11. 모바일 · 호환성'],['security','12. 보안 · 개인정보'],['constraints','13. 필수 원칙 · 금지사항'],['testing','14. 오류 · 예외 · 테스트'],['versioning','15. 버전 · 배포 · 파일'],['current','16. 현재 구현 상태'],['remaining','17. 남은 작업 · 후속 계획']];
const EDIT_FIELDS=['name','icon','group','status','progress','pcVersion','mobileVersion','testStatus','releaseChannel','testUrl','note'];

function isLocalBridge(){return location.port==='8765'||new URL(location.href).searchParams.has('pair')}
function getCredential(){
  const u=new URL(location.href);
  if(isLocalBridge()){
    const p=u.searchParams.get('pair')||localStorage.getItem('devlib_pair_code')||'';
    if(p)localStorage.setItem('devlib_pair_code',p);
    return p;
  }
  let k='';
  if(u.hash.startsWith('#key=')){k=decodeURIComponent(u.hash.slice(5));localStorage.setItem('devlib_view_key',k);history.replaceState({},'',u.pathname+u.search)}
  if(!k)k=u.searchParams.get('key')||'';
  if(k){localStorage.setItem('devlib_view_key',k);u.searchParams.delete('key');history.replaceState({},'',u.pathname+u.search+u.hash)}
  return k||localStorage.getItem('devlib_view_key')||'';
}
async function apiLoad(){
  const cred=getCredential();if(!cred)throw new Error(isLocalBridge()?'연결 코드가 없어요.':'보기/편집 키가 없어요.');
  if(isLocalBridge()){
    const r=await fetch(`/api/state?pair=${encodeURIComponent(cred)}&_=${Date.now()}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return{ok:true,mode:'editor',payload:d,updated_at:d.generatedAt||Date.now(),source:'local'};
  }
  const r=await fetch(`${CLOUD_API}?key=${encodeURIComponent(cred)}&_=${Date.now()}`,{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;
}
async function apiAction(action){
  const cred=getCredential();if(!cred)throw new Error('편집 연결 정보가 없어요.');
  if(isLocalBridge()){
    const r=await fetch(`/api/action?pair=${encodeURIComponent(cred)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action)}),d=await r.json();if(!r.ok||!d.ok){const e=new Error(d.error||`HTTP ${r.status}`);e.data=d;e.status=r.status;throw e}return d;
  }
  const r=await fetch(CLOUD_API,{method:'POST',headers:{'Content-Type':'application/json','X-Devlib-Key':cred},body:JSON.stringify({action})}),d=await r.json();if(!r.ok||!d.ok){const e=new Error(d.error||`HTTP ${r.status}`);e.data=d;e.status=r.status;throw e}return d;
}

function readQueue(){try{return JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]')}catch{return[]}}
function writeQueue(q){localStorage.setItem(QUEUE_KEY,JSON.stringify(q.slice(-100)));updateQueueBadge()}
function enqueue(action){const q=readQueue();if(!action.clientActionId)action.clientActionId=uid('offline');q.push(action);writeQueue(q);return action.clientActionId}
function updateQueueBadge(){const n=readQueue().length,e=$('#queueBadge');if(e){e.textContent=n?`전송 대기 ${n}`:'동기화 완료';e.className='queueBadge'+(n?' pending':'')}}
async function flushQueue(){if(!navigator.onLine||!readQueue().length)return;let q=readQueue(),left=[];for(let i=0;i<q.length;i++){
  try{await apiAction(q[i])}catch(e){if(e.status===409){left.push(q[i]);showStatus('⚠ 같은 항목이 다른 기기에서 수정되어 전송을 멈췄어요. 프로젝트를 열어 확인해 주세요.','warn');left.push(...q.slice(i+1));break}else{left.push(q[i]);left.push(...q.slice(i+1));break}}
}writeQueue(left);if(!left.length){showStatus('✓ 오프라인 변경까지 모두 동기화했어요.');setTimeout(()=>load({silent:true,force:true}),400)}}

function saveCache(data){try{localStorage.setItem('devlib_mobile_cache',JSON.stringify({data,at:Date.now()}))}catch{}}
function readCache(){try{return JSON.parse(localStorage.getItem('devlib_mobile_cache')||'null')}catch{return null}}
function list(xs,empty,limit=8){return arr(xs).slice(0,limit).map(x=>`<li>${esc(x)}</li>`).join('')||`<li class="muted">${esc(empty)}</li>`}
function statusLabel(v){return({active:'진행 중',paused:'잠시 멈춤',done:'완료',archived:'보관'})[v]||'진행 중'}
function testLabel(v){return({unchecked:'미확인',testing:'테스트 중',stable:'안정',experimental:'실험',issue:'문제 있음'})[v]||'미확인'}
function openProjectIds(){return new Set($$('.project[open]').map(x=>x.dataset.pid).filter(Boolean))}
function openSubIds(){return new Set($$('.subdetail[open],.az[open]').map(x=>x.dataset.sid).filter(Boolean))}
function restoreOpen(ids,subs){ids.forEach(id=>{const e=document.querySelector(`.project[data-pid="${CSS.escape(id)}"]`);if(e)e.open=true});subs.forEach(id=>{const e=document.querySelector(`[data-sid="${CSS.escape(id)}"]`);if(e)e.open=true})}
function showStatus(text,kind=''){const s=$('#status');if(!s)return;s.className='status'+(kind?` ${kind}`:'');s.textContent=text}

function fallbackReport(x){const done=arr(x.done),issues=arr(x.issues),todos=arr(x.todos),decisions=arr(x.decisions);let stage='작업 정리 중';if(!x.chatCount)stage='기록 전';else if(issues.length&&done.length)stage='보완 · 안정화 진행 중';else if(todos.length&&done.length)stage='개발 진행 중';else if(todos.length)stage='구현 준비 · 진행 중';else if(done.length&&!issues.length)stage='최근 작업 기준 정리 완료';return{stage,current:x.current||'',latestVersion:arr(x.versions)[0]||'',updatedAt:x.updatedAt||0,chatCount:Number(x.chatCount||0),continuationCount:Number(x.continuationCount||0),doneCount:done.length,issueCount:issues.length,todoCount:todos.length,decisionCount:decisions.length,done,issues,todos,decisions}}
function fallbackGuide(x,r){const sections=AZ.map(([id,title])=>({id,title,items:[]}));const put=(id,vals)=>{const s=sections.find(x=>x.id===id);if(s)s.items=arr(vals)};put('features',x.decisions);put('testing',x.issues);put('remaining',x.todos);return{updatedAt:r.updatedAt,sourceCount:Number(x.chatCount||0),rebuildSourceCount:0,continuationCount:Number(x.continuationCount||0),coverage:sections.filter(s=>s.items.length).length?Math.round(sections.filter(s=>s.items.length).length/sections.length*100):0,coverageMode:'legacy-summary',sections,deprecated:[],versions:arr(x.versions),sources:arr(x.recentChats).slice(0,8)}}
function reportHtml(x){const r=x.report||fallbackReport(x);return `<details class="subdetail" data-sid="${esc(x.id)}-report"><summary><span>📋 진행 현황 보고서</span><small>${esc(r.stage||'')}</small></summary><div class="subbody"><div class="reportHero"><b>${esc(r.stage||'작업 정리 중')}</b><p>${esc(r.current||'아직 정리된 현재 작업이 없어요.')}</p></div><div class="miniStats"><div><b>${Number(r.doneCount||0)}</b><small>완료</small></div><div><b>${Number(r.issueCount||0)}</b><small>버그</small></div><div><b>${Number(r.todoCount||0)}</b><small>남은 일</small></div><div><b>${Number(r.continuationCount||0)}</b><small>계승</small></div></div><div class="grid"><section><h3>✓ 완료</h3><ul>${list(r.done,'기록 없음',10)}</ul></section><section><h3>🐞 문제</h3><ul>${list(r.issues,'없음',10)}</ul></section><section><h3>☐ 다음</h3><ul>${list(r.todos,'없음',10)}</ul></section><section><h3>◆ 결정</h3><ul>${list(r.decisions,'기록 없음',10)}</ul></section></div></div></details>`}
function guideHtml(x){const r=x.report||fallbackReport(x),g=x.guideline?.sections?x.guideline:fallbackGuide(x,r),modeName=g.coverageMode==='full-rescan'?'전체 채팅 재구축 완료':g.coverageMode==='mixed'?'일부 전체 재수집':'기존 기록 기반 임시 정본';const sections=arr(g.sections).length?g.sections:fallbackGuide(x,r).sections;return `<details class="subdetail" data-sid="${esc(x.id)}-guide"><summary><span>📚 A→Z 최신 정본 개발지침서</span><small>${Number(g.coverage||0)}%</small></summary><div class="subbody"><div class="guideMeta"><b>${esc(modeName)}</b><br>참조 ${Number(g.sourceCount||0)}개 · 전체 재수집 ${Number(g.rebuildSourceCount||0)}개 · 계승 ${Number(g.continuationCount||0)}개 · ${fmt(g.updatedAt)}</div>${sections.map(s=>`<details class="az" data-sid="${esc(x.id)}-${esc(s.id)}"><summary>${esc(s.title)} <small>${arr(s.items).length?arr(s.items).length+'개':'미정'}</small></summary><div>${arr(s.items).length?arr(s.items).map(v=>'• '+esc(v)).join('<br>'):'<span class="muted">아직 확인된 최신 지침 없음</span>'}</div></details>`).join('')}${arr(g.deprecated).length?`<details class="az"><summary>🗃 변경·폐기된 옛 지침 ${arr(g.deprecated).length}개</summary><div>${arr(g.deprecated).slice(0,25).map(v=>`• <s>${esc(v.text||'')}</s>${v.replacedBy?` → ${esc(v.replacedBy)}`:''}`).join('<br>')}</div></details>`:''}</div></details>`}
function hubHtml(x){const progress=Math.max(0,Math.min(100,Number(x.progress||0)));return `<div class="hub"><div><b>${esc(statusLabel(x.status))}</b><small>상태</small></div><div><b>${progress}%</b><small>진행률</small></div><div><b>${esc(x.pcVersion||'—')}</b><small>PC</small></div><div><b>${esc(x.mobileVersion||'—')}</b><small>Mobile</small></div><div><b>${esc(testLabel(x.testStatus))}</b><small>테스트</small></div><div><b>${x.releaseChannel==='experimental'?'실험':'안정'}</b><small>채널</small></div></div><div class="progress"><i style="width:${progress}%"></i></div>${x.testUrl?`<a class="testBtn" href="${esc(x.testUrl)}" target="_blank" rel="noopener">📱 모바일 테스트 열기</a>`:`<button class="testBtn disabled" type="button" disabled>📱 모바일 테스트 주소 없음</button>`}`}
function groupOptions(selected=''){return arr(currentData?.payload?.groups).map(g=>`<option value="${esc(g.name)}" ${g.name===selected?'selected':''}>${esc(g.icon||'📁')} ${esc(g.name)}</option>`).join('')}
function projectOptions(selected=''){return arr(currentData?.payload?.projects).map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(p.icon||'📦')} ${esc(p.name)}</option>`).join('')}
function applySearch(){const v=($('#q')?.value||'').trim().toLowerCase();let shown=0;$$('.group').forEach(g=>{let gc=0;g.querySelectorAll('.project').forEach(p=>{const ok=!v||(p.dataset.search||'').includes(v);p.style.display=ok?'':'none';if(ok){gc++;shown++}});g.style.display=gc?'':'none'});$('#empty').style.display=shown?'none':'block'}

function renderInbox(p){const inbox=arr(p.inbox);const root=$('#inboxArea');if(!root)return;if(!inbox.length){root.innerHTML='';return}root.innerHTML=`<section class="inboxBox"><div class="sectionHead"><div><b>✦ 분류 대기</b><small>${inbox.length}개 · 폰에서 바로 정리</small></div></div>${inbox.map(c=>`<article class="inboxItem" data-inbox="${esc(c.id)}"><b>${esc(c.title||'제목 없는 대화')}</b><small>${fmt(c.updatedAt)} · ${esc(c.reason||'확인 필요')}</small>${mode==='editor'?`<select data-assign-select="${esc(c.id)}"><option value="">프로젝트 선택</option>${projectOptions(c.suggestedProjectId||'')}</select><div class="inboxActions"><button data-assign="${esc(c.id)}">프로젝트에 등록</button><button class="danger" data-exclude="${esc(c.id)}">제외</button></div>`:''}</article>`).join('')}</section>`;$$('[data-assign]').forEach(b=>b.onclick=()=>assignInbox(b.dataset.assign));$$('[data-exclude]').forEach(b=>b.onclick=()=>excludeInbox(b.dataset.exclude))}

function render(data,{fromCache=false}={}){
  currentData=data;mode=data.mode||mode;const p=data.payload||{},groups=arr(p.groups),projects=arr(p.projects),stats=p.stats||{},openIds=openProjectIds(),subIds=openSubIds();
  $('#sg').textContent=stats.groups??groups.length;$('#sp').textContent=stats.projects??projects.length;$('#sc').textContent=stats.chats??0;
  $('#updated').textContent=`${mode==='editor'?'PC + 모바일 양방향':'읽기 전용'} · 마지막 동기화 ${fmt(data.updated_at||p.generatedAt)}${p.appVersion?` · PC v${p.appVersion}`:''}`;
  $('#newProject').style.display=mode==='editor'?'inline-flex':'none';
  let html='';for(const g of groups){const ps=projects.filter(x=>(x.group||'기타')===g.name).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));if(!ps.length)continue;html+=`<section class="group"><div class="gtitle"><span>${esc(g.icon||'📁')}</span><div><h2>${esc(g.name)}</h2><small>${ps.length}개 프로젝트</small></div></div>`;for(const x of ps){const guideWords=arr(x.guideline?.sections).flatMap(s=>arr(s.items)).join(' '),search=`${g.name} ${x.name||''} ${x.current||''} ${arr(x.issues).join(' ')} ${arr(x.todos).join(' ')} ${guideWords}`.toLowerCase(),versions=arr(x.versions).slice(0,8).map(v=>`<span class="chip">${esc(v)}</span>`).join('');html+=`<details class="project" data-pid="${esc(x.id||'')}" data-search="${esc(search)}"><summary><span class="picon">${esc(x.icon||'📦')}</span><span class="pmain"><b>${esc(x.name||'프로젝트')}</b><small>${fmt(x.updatedAt)} · ${esc(statusLabel(x.status))} · ${Math.max(0,Math.min(100,Number(x.progress||0)))}%</small></span><span class="arrow">⌄</span></summary><div class="content">${hubHtml(x)}${mode==='editor'?`<button class="editBtn" data-edit="${esc(x.id)}">✎ 프로젝트 편집</button>`:''}${versions?`<div class="versions">${versions}</div>`:''}${reportHtml(x)}${guideHtml(x)}<section class="now"><span>현재 작업</span><p>${esc(x.current||'아직 정리된 현재 작업이 없어요.')}</p></section>${x.note?`<section class="note"><b>메모</b><p>${esc(x.note)}</p></section>`:''}<div class="grid"><section><h3>✓ 최근 완료</h3><ul>${list(x.done,'기록 없음')}</ul></section><section><h3>🐞 문제 · 버그</h3><ul>${list(x.issues,'현재 기록된 문제 없음')}</ul></section><section><h3>☐ 다음 작업</h3><ul>${list(x.todos,'기록 없음')}</ul></section><section><h3>◆ 결정 사항</h3><ul>${list(x.decisions,'기록 없음')}</ul></section></div></div></details>`}html+='</section>'}
  $('#groups').innerHTML=html;restoreOpen(openIds,subIds);renderInbox(p);applySearch();$$('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));
  showStatus(fromCache?`오프라인 · 마지막 저장본 표시 중 · ${clock()}`:`✓ ${mode==='editor'?'양방향 편집':'자동 갱신'} ON · ${clock()}`,fromCache?'warn':'');updateQueueBadge();
}

function fieldValue(x,k){if(k==='note')return x.note||'';return x[k]??''}
function editForm(x={}){return `<label>상위 프로젝트<select id="eGroup">${groupOptions(x.group||arr(currentData?.payload?.groups)[0]?.name||'')}</select></label><label>아이콘<input id="eIcon" value="${esc(x.icon||'📦')}" maxlength="8"></label><label>프로젝트 이름<input id="eName" value="${esc(x.name||'')}"></label><div class="form2"><label>상태<select id="eStatus"><option value="active" ${x.status==='active'||!x.status?'selected':''}>진행 중</option><option value="paused" ${x.status==='paused'?'selected':''}>잠시 멈춤</option><option value="done" ${x.status==='done'?'selected':''}>완료</option><option value="archived" ${x.status==='archived'?'selected':''}>보관</option></select></label><label>진행률<input id="eProgress" type="number" min="0" max="100" value="${Number(x.progress||0)}"></label><label>PC 버전<input id="ePc" value="${esc(x.pcVersion||'')}"></label><label>모바일 버전<input id="eMobile" value="${esc(x.mobileVersion||'')}"></label><label>테스트<select id="eTest"><option value="unchecked" ${x.testStatus==='unchecked'||!x.testStatus?'selected':''}>미확인</option><option value="testing" ${x.testStatus==='testing'?'selected':''}>테스트 중</option><option value="stable" ${x.testStatus==='stable'?'selected':''}>안정</option><option value="experimental" ${x.testStatus==='experimental'?'selected':''}>실험</option><option value="issue" ${x.testStatus==='issue'?'selected':''}>문제 있음</option></select></label><label>채널<select id="eChannel"><option value="stable" ${x.releaseChannel!=='experimental'?'selected':''}>안정</option><option value="experimental" ${x.releaseChannel==='experimental'?'selected':''}>실험</option></select></label></div><label>모바일 테스트 주소<input id="eTestUrl" value="${esc(x.testUrl||'')}" placeholder="https://..."></label><label>메모<textarea id="eNote">${esc(x.note||'')}</textarea></label><div id="sheetConflict"></div>`}
function openEdit(id){const x=arr(currentData?.payload?.projects).find(p=>p.id===id);if(!x)return;creating=false;editingId=id;editingBase=JSON.parse(JSON.stringify(x));conflictAction=null;$('#sheetTitle').textContent=`${x.icon||'📦'} ${x.name}`;$('#sheetBody').innerHTML=editForm(x);openSheet()}
function openCreate(){creating=true;editingId=uid('mobile-project');editingBase={id:editingId,fieldUpdatedAt:{}};conflictAction=null;$('#sheetTitle').textContent='＋ 새 프로젝트';$('#sheetBody').innerHTML=editForm({id:editingId,status:'active',progress:0,testStatus:'unchecked',releaseChannel:'stable'});openSheet()}
function openSheet(){$('#editSheet').classList.add('open');$('#editSheet').setAttribute('aria-hidden','false');setTimeout(()=>$('#eName')?.focus(),80)}
function closeEdit(){$('#editSheet').classList.remove('open');$('#editSheet').setAttribute('aria-hidden','true');editingId='';editingBase=null;creating=false;conflictAction=null}
function collectEdit(){return{name:$('#eName').value.trim(),icon:$('#eIcon').value.trim()||'📦',group:$('#eGroup').value,status:$('#eStatus').value,progress:Math.max(0,Math.min(100,Number($('#eProgress').value)||0)),pcVersion:$('#ePc').value.trim(),mobileVersion:$('#eMobile').value.trim(),testStatus:$('#eTest').value,releaseChannel:$('#eChannel').value,testUrl:$('#eTestUrl').value.trim(),note:$('#eNote').value}}
function optimisticPatch(project,changes,at){for(const [k,v] of Object.entries(changes)){if(k==='note')project.note=v;else project[k]=v}project.fieldUpdatedAt={...(project.fieldUpdatedAt||{})};Object.keys(changes).forEach(k=>project.fieldUpdatedAt[k]=at);project.projectUpdatedAt=at;project.updatedAt=Math.max(Number(project.updatedAt||0),at)}
function showConflict(action,data){conflictAction=action;const c=arr(data?.conflicts);$('#sheetConflict').innerHTML=`<div class="conflictBox"><b>⚠ 같은 항목이 PC/다른 기기에서 먼저 바뀌었어요.</b><p>${c.map(x=>esc(x.field)).join(', ')||'수정 항목'} 충돌을 감지해서 덮어쓰지 않았어요.</p><div class="inboxActions"><button id="conflictReload">최신값 다시 불러오기</button><button id="conflictForce" class="danger">내 값으로 적용</button></div></div>`;$('#conflictReload').onclick=async()=>{await load({force:true});const id=editingId;closeEdit();setTimeout(()=>openEdit(id),120)};$('#conflictForce').onclick=()=>saveEdit(true)}
async function submitOrQueue(action,{optimistic}={}){action.clientActionId=action.clientActionId||uid('mobile');try{const d=await apiAction(action);if(d.conflicts?.length){const e=new Error('conflict');e.status=409;e.data=d;throw e}return{sent:true,data:d}}catch(e){if(e.status===409)throw e;if(!navigator.onLine||/fetch|network|Failed/i.test(String(e.message||e))){enqueue(action);optimistic?.();return{sent:false,queued:true}}throw e}}
async function saveEdit(force=false){const values=collectEdit();if(!values.name){showStatus('프로젝트 이름을 입력해 주세요.','warn');return}const btn=$('#sheetSave');btn.disabled=true;btn.textContent='저장 중…';try{
  const at=Date.now();if(creating){const action={type:'project_create',projectId:editingId,...values,updatedAt:at,clientActionId:uid('create')};await submitOrQueue(action,{optimistic:()=>{currentData.payload.projects.push({id:editingId,...values,fieldUpdatedAt:Object.fromEntries(EDIT_FIELDS.map(k=>[k,at])),projectUpdatedAt:at,updatedAt:at,chatCount:0,issues:[],todos:[],done:[],decisions:[],versions:[]})}});closeEdit();await load({silent:true,force:true}).catch(()=>render(currentData));showStatus(navigator.onLine?'✓ 새 프로젝트를 저장했어요.':'✓ 오프라인 저장됨 · 연결되면 자동 전송');return}
  const x=arr(currentData?.payload?.projects).find(p=>p.id===editingId);if(!x)return;const changes={};for(const k of EDIT_FIELDS){if(String(fieldValue(editingBase,k)??'')!==String(values[k]??''))changes[k]=values[k]}if(!Object.keys(changes).length){closeEdit();return}const action={type:'project_patch',projectId:x.id,changes,baseFieldUpdatedAt:{...(editingBase.fieldUpdatedAt||{})},updatedAt:at,clientActionId:uid('patch'),forceFields:force?Object.keys(changes):[]};const result=await submitOrQueue(action,{optimistic:()=>{optimisticPatch(x,changes,at);render(currentData)}});if(result.sent)optimisticPatch(x,changes,at);closeEdit();render(currentData);showStatus(result.queued?'✓ 오프라인 변경 저장됨 · 인터넷 연결 시 자동 전송':'✓ 모바일 변경 저장됨 · PC에도 자동 반영');setTimeout(()=>load({silent:true,force:true}),600)
}catch(e){if(e.status===409){showConflict(conflictAction||{type:'project_patch',projectId:editingId,changes:collectEdit(),baseFieldUpdatedAt:editingBase?.fieldUpdatedAt||{},updatedAt:Date.now()},e.data||{});showStatus('⚠ 동시 수정 충돌을 감지했어요. 덮어쓰지 않았습니다.','warn')}else showStatus('저장 실패: '+e.message,'bad')}finally{btn.disabled=false;btn.textContent='저장'}}

async function assignInbox(id){const select=document.querySelector(`[data-assign-select="${CSS.escape(id)}"]`),projectId=select?.value;if(!projectId){showStatus('등록할 프로젝트를 선택해 주세요.','warn');return}const action={type:'assign_inbox',chatId:id,projectId,updatedAt:Date.now(),clientActionId:uid('assign')};try{const r=await submitOrQueue(action,{optimistic:()=>{currentData.payload.inbox=arr(currentData.payload.inbox).filter(x=>x.id!==id);render(currentData)}});currentData.payload.inbox=arr(currentData.payload.inbox).filter(x=>x.id!==id);render(currentData);showStatus(r.queued?'✓ 오프라인 분류 저장됨 · 연결되면 전송':'✓ 프로젝트에 등록했어요.')}catch(e){showStatus('분류 실패: '+e.message,'bad')}}
async function excludeInbox(id){const action={type:'exclude_inbox',chatId:id,updatedAt:Date.now(),clientActionId:uid('exclude')};try{const r=await submitOrQueue(action,{optimistic:()=>{currentData.payload.inbox=arr(currentData.payload.inbox).filter(x=>x.id!==id);render(currentData)}});currentData.payload.inbox=arr(currentData.payload.inbox).filter(x=>x.id!==id);render(currentData);showStatus(r.queued?'✓ 오프라인 제외 저장됨 · 연결되면 전송':'✓ 분류대기에서 제외했어요.')}catch(e){showStatus('제외 실패: '+e.message,'bad')}}

async function load({silent=false,force=false}={}){if(loading&&!force)return;loading=true;if(!silent)showStatus('최신 상태 확인 중…');try{const d=await apiLoad();const sig=`${d.updated_at||''}|${d.payload?.generatedAt||''}|${d.payload?.appVersion||''}|${d.mode||''}`;saveCache(d);if(force||sig!==lastSignature){lastSignature=sig;render(d)}else showStatus(`✓ ${mode==='editor'?'양방향 편집':'자동 갱신'} ON · ${clock()} · 변경 없음`);await flushQueue()}catch(e){const c=readCache();if(c?.data){if(!currentData)render(c.data,{fromCache:true});else showStatus('인터넷 연결 대기 중 · 마지막 저장본 유지','warn')}else showStatus('데이터를 불러오지 못했어요: '+e.message,'bad')}finally{loading=false;updateQueueBadge()}}

$('#q')?.addEventListener('input',applySearch);$('#refresh')?.addEventListener('click',()=>load({force:true}));$('#newProject')?.addEventListener('click',openCreate);$('#sheetCancel')?.addEventListener('click',closeEdit);$('#sheetSave')?.addEventListener('click',()=>saveEdit(false));$('#editSheet')?.addEventListener('click',e=>{if(e.target.id==='editSheet')closeEdit()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')load({silent:true,force:true})});window.addEventListener('focus',()=>load({silent:true}));window.addEventListener('pageshow',()=>load({silent:true,force:true}));window.addEventListener('online',()=>{flushQueue();load({silent:true,force:true})});setInterval(()=>{if(document.visibilityState==='visible')load({silent:true})},POLL_MS);updateQueueBadge();load({force:true});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
