from pathlib import Path
p=Path('mobile/idol/index.html'); s=p.read_text(encoding='utf-8')
def rep(a,b,n=1):
 global s
 if s.count(a)!=n: raise SystemExit(f'count {s.count(a)} != {n}: {a[:50]!r}')
 s=s.replace(a,b,n)
rep('content="2.5.2"','content="2.5.3"')
marker='.relation-romance-pill{font-size:.68rem;padding:4px 9px;font-weight:850}\n</style>'
css='''\n\n<style id="idol-v253-ui-relation-audit">\n#graph-legend.legend-wrap{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:5px 6px;padding:4px 0;max-width:100%;}\n#graph-legend .legend-label{font-size:.68rem;font-weight:800;color:var(--text-sub);margin-right:2px;}\n#graph-legend .legend-item{min-height:24px;padding:3px 7px;border-radius:8px;font-size:.68rem;font-weight:700;white-space:nowrap;background:var(--bg);border:1px solid var(--border);color:var(--text-sub);}\n#graph-legend .legend-text{border-color:color-mix(in srgb,var(--legend-color) 42%,var(--border));box-shadow:inset 0 -2px 0 var(--legend-color);}\n#graph-legend .legend-divider{width:1px;height:18px;background:var(--border);margin:0 2px;}\n#graph-legend .legend-romance.lover{color:#d93f7c;border-color:rgba(217,63,124,.28);background:rgba(255,91,153,.08);}\n#graph-legend .legend-romance.ex{color:var(--danger);border-color:rgba(231,76,60,.24);background:rgba(231,76,60,.06);}\n#graph-legend .legend-dot{display:none!important;}\n#tab-settings .settings-row > label{flex:0 0 116px;min-width:116px;}\n#tab-settings .settings-control{width:225px!important;max-width:225px!important;min-width:225px!important;flex:0 0 225px;min-height:44px;height:44px;}\n#tab-settings #settings-group-name + .btn{min-height:44px;height:44px;}\n@media(max-width:600px){#tab-settings .settings-row:not(.settings-row-check){align-items:stretch;}#tab-settings .settings-row:not(.settings-row-check) > label{flex:0 0 100%;min-width:0;margin-bottom:1px;}#tab-settings .settings-control{width:100%!important;max-width:none!important;min-width:0!important;flex:1 1 100%;}#tab-settings #settings-group-name + .btn{width:100%;}#graph-legend.legend-wrap{justify-content:flex-start;}#graph-legend .legend-label{flex:0 0 100%;}}\n</style>'''
rep(marker,marker+css)
rep('class="input" style="max-width:180px" placeholder="그룹명"','class="input settings-control" placeholder="그룹명"')
rep('class="input" style="max-width:130px" onchange="onChangeTheme(this.value)"','class="input settings-control" onchange="onChangeTheme(this.value)"')
rep('class="input" style="max-width:160px" onchange="onChangeMode(this.value)"','class="input settings-control" onchange="onChangeMode(this.value)"')
rep('연애 자체 허용 (해제 시 고백·연인 전환 전부 차단)','연애 자체 허용 (해제 시 신규 고백·연애 진행 차단, 기존 연인 유지)')
rep('→ 3일 / 이후 이별 후 이벤트','→ 3일 / 이후 우정·이별 후 이벤트로 회복 가능 · 호감도 100 이상 재결합')
a='  if (r.history.length) r.lastEventDay = Math.max(r.lastEventDay, ...r.history.map(h => h.day));'
i="""\n\n  // v25.3 relation integrity: keep only one official current romance state.\n  const hasLoverTag = r.tags.includes('lover');\n  const hasExTag = r.tags.includes('exLover');\n  if (hasLoverTag && hasExTag) {\n    const official = [...r.history].reverse().find(h => ['breakup','auto_breakup','confession','auto_confession','reunion'].includes(h.type));\n    const ended = official && ['breakup','auto_breakup'].includes(official.type);\n    const joined = official && ['confession','auto_confession','reunion'].includes(official.type);\n    if (ended || (!joined && r.stage !== 'lover')) r.tags = r.tags.filter(t => t !== 'lover');\n    else r.tags = r.tags.filter(t => t !== 'exLover');\n  }\n  if (r.tags.includes('lover')) {\n    r.tags = r.tags.filter(t => !['exLover','flirting','crush','romanticInterest'].includes(t)); r.avoidDaysLeft=0; r.confessionPending=false;\n  } else if (r.tags.includes('exLover')) { r.tags=r.tags.filter(t=>t!=='lover'); r.confessionPending=false; }"""
rep(a,a+i)
rep('  const exAwkClear = s.exAwkwardClear || 80;\n','')
rep("    if (rel.affection <= exAwkClear) return ['after_breakup'];\n    if (rel.affection >= reunionR) return ['friendship','flirting','date','reunion'];\n    return ['after_breakup'];","    // v25.3: after avoidance ends, friendship can rebuild an ex relationship.\n    if (rel.affection < reunionR) return ['after_breakup','friendship'];\n    return ['friendship','flirting','date','reunion'];")
rep("  container.innerHTML = tiers.map(t=>\n    `<span class=\"legend-item\"><span class=\"legend-dot\" style=\"background:${STAGE_COLORS[t.id]||'#999'}\"></span>${t.icon} ${t.label}</span>`\n  ).join('') + `<span class=\"legend-item\">💗 연인</span><span class=\"legend-item\">💔 전 연인</span>`;","  container.innerHTML = `<span class=\"legend-label\">친밀도</span>` + tiers.map(t=>\n    `<span class=\"legend-item legend-text\" style=\"--legend-color:${STAGE_COLORS[t.id]||'#999'}\">${t.label}</span>`\n  ).join('') + `<span class=\"legend-divider\" aria-hidden=\"true\"></span><span class=\"legend-item legend-romance lover\">💗 연인</span><span class=\"legend-item legend-romance ex\">💔 전 연인</span>`;")
rep("  if (isEx && !isAvoiding && rel.affection <= (settings.exAwkwardClear||80)\n      && !['after_breakup','avoid'].includes(type)) return '이별 후 단계 — 이별 후 이벤트만 가능';\n  if (isEx && rel.affection < exOkMin && ['date','flirting','friendship'].includes(type))","  if (isEx && rel.affection < exOkMin && ['date','flirting'].includes(type))")
rep("&& ['friendship','flirting','date'].includes(type)) {","&& ['flirting','date'].includes(type)) {",2)
p.write_text(s,encoding='utf-8')
